services:
  - type: web
    name: final-audio-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port 10000
